name: Sync with Upstream

on:
  # Run weekly on Sunday at midnight UTC
  schedule:
    - cron: '0 0 * * 0'
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout desktop-extension-stable branch
        uses: actions/checkout@v4
        with:
          ref: desktop-extension-stable
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/zerodha/kite-mcp-server.git || true
          git remote -v

      - name: Fetch upstream changes
        run: |
          git fetch upstream
          git fetch origin

      - name: Merge upstream changes
        id: merge
        run: |
          # Try to merge upstream/master into desktop-extension-stable
          if git merge upstream/master -m "chore: sync with upstream master"; then
            echo "merge_status=success" >> $GITHUB_OUTPUT
            echo "✅ Successfully merged upstream changes"
          else
            echo "merge_status=conflict" >> $GITHUB_OUTPUT
            echo "❌ Merge conflicts detected"
            git merge --abort
            exit 1
          fi

      - name: Push changes
        if: steps.merge.outputs.merge_status == 'success'
        run: |
          if git diff --quiet origin/desktop-extension-stable; then
            echo "No changes to push"
          else
            git push origin desktop-extension-stable
            echo "✅ Pushed merged changes to origin"
          fi

      - name: Create sync report issue
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const date = new Date().toISOString().split('T')[0];
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `[Sync Failed] Upstream sync conflicts - ${date}`,
              body: `## Upstream Sync Failed
              
              The automated sync with upstream failed due to merge conflicts.
              
              ### Action Required
              1. Checkout the \`desktop-extension-stable\` branch locally
              2. Run \`git fetch upstream\`
              3. Manually resolve conflicts with \`git merge upstream/master\`
              4. Push the resolved changes
              
              ### Commands
              \`\`\`bash
              git checkout desktop-extension-stable
              git fetch upstream
              git merge upstream/master
              # Resolve conflicts
              git add .
              git commit
              git push origin desktop-extension-stable
              \`\`\`
              
              [View Workflow Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
              `,
              labels: ['upstream-sync', 'needs-attention']
            });